export const Data = [
  {
    title: `นายไพฑูรย์ ธนสีลังกูร`,
    secondary: `ทำหน้าที่ประสานงานการจัดตั้ง`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2535  จนถึงปี พ.ศ. 2541`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายอักษรศิลป์ แก้วมหาวงศ์`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2541  จนถึงปี พ.ศ. 2549`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายยงยุทธ จันทวารา`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2550  จนถึงปี พ.ศ. 2553`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายวาสิทธิ์ พวงสวัสดิ์`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2555  จนถึงปี พ.ศ. -2556`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายโสภา มะเครือสี`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2556  จนถึงปี พ.ศ. 2563`,
    img: `/images/ผู้บริหาร/ผอโสภา.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายวิโรจน์ ธิมา`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2563  จนถึงปี พ.ศ. 2566`,
    img: `/images/ผู้บริหาร/ผอวิโรจน์1.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
];
export const Data1 = [
  {
    title: `นางสาววิภาวรรณ สีแดด`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายพัฒนากิจการนักเรียน นักศึกษา`,
    img: `/images/ผู้บริหาร/2.webp`,
    phone: `045-810-777`,
    email: `wipawan@ktltc.ac.th`,
    lineId: `wipawan_line`,
  },
  {
    title: `นายสมศักดิ์ จันทานิตย์`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายแผนงานและความร่วมมือ`,
    img: `/images/ผู้บริหาร/3.webp`,
    phone: `045-810-777`,
    email: `somsak@ktltc.ac.th`,
    lineId: `somsak_line`,
  },
  {
    title: `นายอาทร ศรีมะณี`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายวิชาการ`,
    img: `/images/ผู้บริหาร/4.webp`,
    phone: `045-810-777`,
    email: `atorn@ktltc.ac.th`,
    lineId: `atorn_line`,
  },
  {
    title: `นางสาวภวิกา โพธิ์ขาว`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายบริหารทรัพยากร`,
    img: `/images/ผู้บริหาร/5.webp`,
    phone: `045-810-777`,
    email: `phawika@ktltc.ac.th`,
    lineId: `phawika_line`,
  },
];

export const DataCommittee = [
  {
    title: `นายบุญส่ง พรหมมานนท์`,
    secondary: `ประธานกรรมการ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture2.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายบุญแต่ง ป้อมหิน`,
    secondary: `กรรมการผู้แทนครูหรือคณาจารย์`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture14.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายสุริชัย คำศรี`,
    secondary: `กรรมการผู้แทนผู้ปกครอง`,
    description: ``,
    img: `/images/error.webp`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายเทพทัย แก่นสาร`,
    secondary: `กรรมการผู้แทนองค์กรชุมชน`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture9.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายมงคล สิงห์ค้า`,
    secondary: `กรรมการผู้แทนองค์กรปกครองส่วนท้องถิ่น`,
    description: ``,
    img: `/images/error.webp`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายสาคร บุญชู`,
    secondary: `กรรมการผู้แทนศิษย์เก่า`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture8.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `พระครูไพโรจน์กิตยาภรณ์`,
    secondary: `กรรมการผู้แทนพระภิกษุสงฆ์หรือผู้แทนองค์กรศาสนาอื่นในพื้นที่`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture10.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `พระครูเมตตาธรรมสิริ`,
    secondary: `กรรมการผู้แทนพระภิกษุสงฆ์หรือผู้แทนองค์กรศาสนาอื่นในพื้นที่`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture12.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายภูมิธฤทธิ์ พงษ์กิติทราธรณ์`,
    secondary: `กรรมการผู้แทนสถานประกอบการ`,
    description: ``,
    img: `/images/error.webp`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `ว่าที่ร้อยตรี ชัยพร สีตะวัน`,
    secondary: `กรรมการผู้แทนสถานประกอบการ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture5.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายณรงค์ แก้วสาลี`,
    secondary: `กรรมการผู้แทนสถานประกอบการ`,
    description: ``,
    img: `/images/error.webp`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายวิวัฒน์ ศิลาอ่อน`,
    secondary: `กรรมการผู้แทนสถานประกอบการ`,
    description: ``,
    img: `/images/error.webp`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายณัฏฐิวัตร คงบำรุง`,
    secondary: `กรรมการผู้แทนสถานประกอบการ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture6.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายพงษ์ศักดิพล ทาแก้ว`,
    secondary: `กรรมการผู้ทรงคุณวุฒิ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture1.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นางสุภาภรณ์ บุญเริ่ม`,
    secondary: `กรรมการผู้ทรงคุณวุฒิ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture4.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นางจารุณี โล่รัตน์กุล`,
    secondary: `กรรมการผู้ทรงคุณวุฒิ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture11.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายสัมฤทธิ์ กาญจนสุนทร`,
    secondary: `กรรมการผู้ทรงคุณวุฒิ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture3.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นายพรชัย คติกำจร`,
    secondary: `กรรมการผู้ทรงคุณวุฒิ`,
    description: ``,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture7.jpg`,
    phone: ``,
    email: ``,
    lineId: ``,
  },
  {
    title: `นางสาวทักษิณา ชมจันทร์`,
    secondary: `กรรมการและเลขานุการ`,
    description: `ผู้อำนวยการวิทยาลัยเทคนิคกันทรลักษ์`,
    img: `/คณะกรรมการวิทยาลัยเทคนิคกันทรลักษ์/Picture13.jpg`,
    phone: `045-810-777`,
    email: `director@ktltc.ac.th`,
    lineId: `director_line`,
  },
];
