export const Data = [
  {
    title: `นายไพฑูรย์ ธนสีลังกูร`,
    secondary: `ทำหน้าที่ประสานงานการจัดตั้ง`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2535  จนถึงปี พ.ศ. 2541`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายอักษรศิลป์ แก้วมหาวงศ์`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2541  จนถึงปี พ.ศ. 2549`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายยงยุทธ จันทวารา`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2550  จนถึงปี พ.ศ. 2553`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายวาสิทธิ์ พวงสวัสดิ์`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2555  จนถึงปี พ.ศ. -2556`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายโสภา มะเครือสี`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2556  จนถึงปี พ.ศ. 2563`,
    img: `/images/ผู้บริหาร/ผอโสภา.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายวิโรจน์ ธิมา`,
    secondary: `ตำแหน่งผู้อำนวยการสถานศึกษา`,
    description: `เริ่มปฏิบัติงาน เมื่อปี พ.ศ. พ.ศ. 2563  จนถึงปี พ.ศ. 2566`,
    img: `/images/ผู้บริหาร/ผอวิโรจน์1.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
];
export const Data1 = [
  {
    title: `นางสาววิภาวรรณ สีแดด`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายพัฒนากิจการนักเรียน นักศึกษา`,
    img: `/images/ผู้บริหาร/2.webp`,
    phone: `045-810-777`,
    email: `wipawan@ktltc.ac.th`,
    lineId: `wipawan_line`,
  },
  {
    title: `นายสมศักดิ์ จันทานิตย์`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายแผนงานและความร่วมมือ`,
    img: `/images/ผู้บริหาร/3.webp`,
    phone: `045-810-777`,
    email: `somsak@ktltc.ac.th`,
    lineId: `somsak_line`,
  },
  {
    title: `นายอาทร ศรีมะณี`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายวิชาการ`,
    img: `/images/ผู้บริหาร/4.webp`,
    phone: `045-810-777`,
    email: `atorn@ktltc.ac.th`,
    lineId: `atorn_line`,
  },
  {
    title: `นางสาวภวิกา โพธิ์ขาว`,
    secondary: `รองผู้อำนวยการ`,
    description: `ฝ่ายบริหารทรัพยากร`,
    img: `/images/ผู้บริหาร/5.webp`,
    phone: `045-810-777`,
    email: `phawika@ktltc.ac.th`,
    lineId: `phawika_line`,
  },
];

export const DataCommittee = [
  {
    title: `นายวิทยา บุญยืน`,
    secondary: `ประธานกรรมการ`,
    description: `ผู้ทรงคุณวุฒิด้านการบริหารการศึกษา`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นางสาวทักษิณา ชมจันทร์`,
    secondary: `กรรมการและเลขานุการ`,
    description: `ผู้อำนวยการวิทยาลัยเทคนิคกันทรลักษ์`,
    img: `/images/ผู้บริหาร/1.webp`,
    phone: `045-810-777`,
    email: `director@ktltc.ac.th`,
    lineId: `director_line`,
  },
  {
    title: `นายสมชาย รักษาสัตย์`,
    secondary: `กรรมการผู้แทนครู`,
    description: `ผู้แทนครูและบุคลากรทางการศึกษา`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `somchay@ktltc.ac.th`,
    lineId: `somchay_line`,
  },
  {
    title: `นายประสิทธิ์ สุวรรณภูมิ`,
    secondary: `กรรมการผู้แทนองค์กรปกครองส่วนท้องถิ่น`,
    description: `ผู้แทนองค์การบริหารส่วนจังหวัดศรีสะเกษ`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `prasit@ktltc.ac.th`,
    lineId: `prasit_line`,
  },
  {
    title: `นายธีระ คำศิลา`,
    secondary: `กรรมการผู้แทนผู้ปกครอง`,
    description: `ผู้แทนผู้ปกครองนักเรียน นักศึกษา`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นางสาวกัลยา พลแสน`,
    secondary: `กรรมการผู้แทนนักเรียน นักศึกษา`,
    description: `ผู้แทนนักเรียน นักศึกษาของวิทยาลัย`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นายอนันต์ เพียงแก้ว`,
    secondary: `กรรมการผู้แทนศิษย์เก่า`,
    description: `ผู้แทนศิษย์เก่าวิทยาลัยเทคนิคกันทรลักษ์`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
  {
    title: `นางรัตนา บุญประกอบ`,
    secondary: `กรรมการผู้ทรงคุณวุฒิ`,
    description: `ผู้ทรงคุณวุฒิด้านการเงินและบัญชี`,
    img: `/images/error.webp`,
    phone: `045-810-777`,
    email: `info@ktltc.ac.th`,
    lineId: `ktltc-official`,
  },
];
