// ชื่อข่าว 
export const DataPressrelease = {
  Item: [
    { title: `ข่าวประชาสัมพันธ์`, },
    { title: `วิทยาลัยเทคนิคกันทรลักษ์`, },
  ],
};

// วันที่ลงข้อมูล 
export const DataDate = [{ date: `6 พฤศจิกายน 2568` }];

// คำอธิบายข่าว
export const Description = [
  { description: `นางสาวทักษิณา ชมจันทร์ ผู้อำนวยการวิทยาลัยเทคนิคกันทรลักษ์ พร้อมด้วย คณะผู้บริหาร ครู และนักเรียน นักศึกษา ชั้นปีที่ 1 เข้าร่วมพิธีเปิดงานประชุมวิชาการองค์การนักวิชาชีพในอนาคตแห่งประเทศไทย (อวท.) ระดับสถานศึกษา ประจำปีการศึกษา 2568 เเละพิธีเชิดชูเกียรติสมาชิกดีเด่น ณ หอประชุมผามออีแดง วิทยาลัยเทคนิคกันทรลักษ์` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
  // { description: `` },
];

// ลิงค์
export const TageLink = [
  {
    tage: `รูปภาพเพิ่มเติม https://drive.google.com/.../17sceW_P1qHIAtuV...`,
    href: `https://l.facebook.com/l.php?u=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F17sceW_P1qHIAtuV-0EVghbCrzoiUtszY%3Ffbclid%3DIwZXh0bgNhZW0CMTAAYnJpZBExT3lqZndTWlNiSEJLVGt3NHNydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR4aUJCxU7VP4Ix8xkPx1ndUC6OifHG-X5D9xnvW0Zv-WXKBH5PCtYUG16mfaQ_aem_dSA7hgyqRwuzrPngqb_Zbw&h=AT0FOpNke4ORin5_cNOyCdJd3RBomcfki6UL_7tj_di8dIDMQoYG-SZfTf23tEafQtTmMovLmIi8M73X10klalMTpT-GDxXHDCq2NRsZHf-AmMjtyNkbqK2k1uGFq4oGGDVfmrivBj4BO314&__tn__=-UK-R&c[0]=AT37rXK1iA79luhkmbubpvppy9BLd7dtrI99X2Dc9VBqCe1J_jxXQS4wpG7BTIW8Z9WA7QFrHc6asYi4xx5UjbiZC2t6t2rME4qGRrDKX1PMl5HeI49akJOQzRslrLeCItNa0OyzPzkO9gzc0mpDkTlBk6bGRvEggLvJu6PSPv2Eu9sjpyWuhYvqQY0DssiVY_YKMl8ioilHCiOvVWMgAnV2QQ`,
  },

  // {
  // tage: ``,
  // href: ``,
  // },
]

// รูปภาพ
export const ImageItem = [
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/01.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/02.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/03.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/04.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/05.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/06.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/07.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/08.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/09.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/10.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/11.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/12.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/13.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/14.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/15.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/16.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/17.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/18.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/19.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/20.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/21.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/22.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/23.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/24.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/25.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/26.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/27.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/28.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/29.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/30.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/31.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/32.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/33.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/34.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/35.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/36.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/37.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/38.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/39.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/40.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/41.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/42.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/43.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/44.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/45.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/46.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/47.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/48.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/49.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/50.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/51.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/52.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/53.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/54.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/55.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/56.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/57.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/58.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/59.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/60.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/61.webp" },
  { imgs: "/images/ข่าวประชาสัมพันธ์/2568/พฤศจิกายน/6/00.webp" },
]
