export const paragraphsEn = [
  "The quick brown fox jumps over the lazy dog.",
  "Programming is the art of telling another human what one wants the computer to do.",
  "To be or not to be, that is the question.",
  "All that glitters is not gold.",
  "In the middle of difficulty lies opportunity.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "A journey of a thousand miles begins with a single step.",
  "Code is like humor. When you have to explain it, it's bad.",
  "First, solve the problem. Then, write the code.",
  "Knowledge is power.",
  "Simplicity is the soul of efficiency.",
  "Talk is cheap. Show me the code.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "Testing leads to failure, and failure leads to understanding.",
  "Make it work, make it right, make it fast.",
  "The best way to predict the future is to invent it.",
  "Stay hungry, stay foolish.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Quality is not an act, it is a habit.",
  "Do or do not. There is no try.",
  "Believe you can and you're halfway there.",
  "If you can dream it, you can do it.",
  "It always seems impossible until it's done.",
  "Be the change that you wish to see in the world.",
  "Software is a great combination between artistry and engineering.",
  "You might not think that programmers are artists, but programming is an extremely creative profession.",
  "Learning to write programs stretches your mind, and helps you think better, creates a way of thinking about things that I think is helpful in all domains.",
  "The computer was born to solve problems that did not exist before.",
  "A good programmer is someone who always looks both ways before crossing a one-way street.",
  "One man's constant is another man's variable.",
  "Computers are good at following instructions, but not at reading your mind.",
  "There are two ways to write error-free programs; only the third one works.",
  "Truth can only be found in one place: the code.",
  "The most disastrous thing that you can ever learn is your first programming language.",
  "It's not a bug, it's an undocumented feature.",
  "Deleted code is debugged code.",
  "Programmers are not to be measured by their ingenuity and their logic but by the completeness of their case analysis.",
  "Everything is a widget in Flutter, but everything is an object in JavaScript.",
  "React makes it painless to create interactive UIs.",
  "Next.js gives you the best developer experience with all the features you need for production.",
  "Tailwind CSS is a utility-first CSS framework for rapidly building custom user interfaces.",
  "Typescript is JavaScript with syntax for types.",
  "A database is an organized collection of data, generally stored and accessed electronically from a computer system.",
  "The internet is a vast network that connects computers all over the world.",
  "Machine learning is a field of inquiry devoted to understanding and building methods that 'learn'.",
  "Artificial intelligence is intelligence demonstrated by machines, as opposed to natural intelligence displayed by animals including humans.",
  "Data structures and algorithms are the fundamentals of computer science.",
  "The cloud is just someone else's computer."
];
