import { MongoClient } from "mongodb";

const uri = "mongodb://nut:Nut29122539@127.0.0.1:27017/ktltc_db?authSource=admin";
const client = new MongoClient(uri);

async function run() {
  try {
    await client.connect();
    console.log("Connected to MongoDB!");
    const db = client.db("ktltc_db");

    // Clear existing custom menus to avoid duplicates
    await db.collection("custom_menus").deleteMany({});
    console.log("Cleared existing custom menus.");

    const menus = [
      // 1. Sidebar Menus
      {
        title: "ระบบติดตาม PDCA",
        href: "/pdca",
        icon: "Activity",
        desc: "ติดตามและจัดการโครงการพัฒนาคุณภาพการศึกษาแบบครบวงจร",
        workspace: "staff",
        displayIn: "both",
        permissionKey: "custom_pdca",
        createdAt: new Date(),
      },
      {
        title: "บันทึกข้อความทั่วไป",
        href: "/GeneralMemoPage",
        icon: "FileText",
        desc: "ระบบสร้างเอกสารบันทึกข้อความ",
        workspace: "staff",
        displayIn: "both",
        permissionKey: "custom_memo",
        createdAt: new Date(),
      },

      // 2. Student Workspace
      {
        title: "เช็คชื่อเข้าแถวหน้าเสาธง",
        href: "/student/flagpole",
        icon: "Clock",
        desc: "ระบบเช็คชื่อด้วยพิกัด GPS",
        workspace: "student",
        displayIn: "dashboard",
        permissionKey: "student_dashboard",
        createdAt: new Date(),
      },
      {
        title: "ศูนย์การศึกษาระบบทวิภาคี (DVE)",
        href: "/dashboard/dve/student",
        icon: "BookOpen",
        desc: "ระบบบันทึกสมุดฝึกงาน",
        workspace: "student",
        displayIn: "dashboard",
        permissionKey: "access_dve_student",
        createdAt: new Date(),
      },
      {
        title: "แชท / กล่องข้อความ",
        href: "/dashboard/chat",
        icon: "MessageSquare",
        desc: "ติดต่อสื่อสารกับอาจารย์",
        workspace: "student",
        displayIn: "dashboard",
        permissionKey: "student_dashboard",
        createdAt: new Date(),
      },

      // 3. Teacher Workspace
      {
        title: "ข้อมูลนักเรียนในที่ปรึกษา / แผนก",
        href: "/teacher/students",
        icon: "Users",
        desc: "ระบบตรวจสอบรายชื่อประจำแผนก",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_teacher_students",
        createdAt: new Date(),
      },
      {
        title: "ระบบสแกนเข้า-ออก (Gate)",
        href: "/teacher/gate-scanner",
        icon: "ScanLine",
        desc: "ติดตามนักเรียนออกนอกสถานศึกษา หรือกลับเข้าวิทยาลัย",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_gate_scanner",
        createdAt: new Date(),
      },
      {
        title: "หน้าติดตามตำแหน่ง (GPS)",
        href: "/teacher/tracking",
        icon: "Navigation",
        desc: "แสดงพิกัดนักเรียนแบบ Real-time",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_gps_tracking",
        createdAt: new Date(),
      },
      {
        title: "ระบบนิเทศนักศึกษาฝึกงาน",
        href: "/dashboard/supervision",
        icon: "ClipboardList",
        desc: "บันทึกและตรวจสอบข้อมูลการนิเทศ",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_dve_teacher",
        createdAt: new Date(),
      },
      {
        title: "ระบบตรวจสอบแผนการสอน",
        href: "/dashboard/director/lesson-plans",
        icon: "FileText",
        desc: "อัปโหลดแผนการสอน",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_lesson_plans",
        createdAt: new Date(),
      },
      {
        title: "ระบบประเมินผลการปฏิบัติงาน / DPA",
        href: "/dashboard/director/dpa-evaluation",
        icon: "ShieldCheck",
        desc: "ระบบประเมินครู DPA",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_dpa_evaluation",
        createdAt: new Date(),
      },
      {
        title: "ชุมชนการเรียนรู้ทางวิชาชีพ (PLC)",
        href: "/dashboard/director/plc",
        icon: "Users",
        desc: "บันทึกชั่วโมง PLC",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_plc",
        createdAt: new Date(),
      },
      {
        title: "ระบบรายงานการปฏิบัติงาน",
        href: "/work-reports",
        icon: "ClipboardList",
        desc: "ตรวจสอบและติดตามรายงานการปฏิบัติงานรายบุคคล",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_work_reports",
        createdAt: new Date(),
      },
      {
        title: "ระบบดูแลช่วยเหลือนักเรียน",
        href: "/dashboard/director/student-care",
        icon: "ClipboardList",
        desc: "คัดกรองนักเรียน และรายงานเยี่ยมบ้าน (คป.02 / คป.11)",
        workspace: "teacher",
        displayIn: "dashboard",
        permissionKey: "access_student_care",
        createdAt: new Date(),
      },

      // 4. Staff / HR Workspace
      {
        title: "คลังเอกสารดิจิทัล (Drive)",
        href: "/dashboard/drive",
        icon: "HardDrive",
        desc: "ระบบจัดเก็บไฟล์ส่วนกลาง",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_drive",
        createdAt: new Date(),
      },
      {
        title: "จัดการข่าวสาร / ประชาสัมพันธ์",
        href: "/dashboard/news",
        icon: "Newspaper",
        desc: "จัดการข่าวสาร",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_news",
        createdAt: new Date(),
      },
      {
        title: "จัดการการเลือกตั้ง",
        href: "/dashboard/election",
        icon: "Users",
        desc: "ควบคุมและดูแลระบบการเลือกตั้งทั้งหมด สร้าง แก้ไข และลบการเลือกตั้ง",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_elections",
        createdAt: new Date(),
      },
      {
        title: "ระบบถาม-ตอบ Q & A",
        href: "/dashboard/questions",
        icon: "MessageSquare",
        desc: "ตอบคำถามและข้อร้องเรียน",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_qa",
        createdAt: new Date(),
      },
      {
        title: "แก้ไขข้อมูลการลงเข้าแถว",
        href: "/dashboard/flagpole-data-management",
        icon: "ClipboardList",
        desc: "แก้ไขพิกัด เวลา เช็คชื่อ",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_flagpole_data",
        createdAt: new Date(),
      },
      {
        title: "สถิติภาพรวม การเข้าแถวเสาธง",
        href: "/dashboard/flagpole-dashboard",
        icon: "Layers",
        desc: "สรุปสถิติการเข้าแถวเสาธง โดยแบ่งตามระดับชั้นและจำนวนนักเรียนที่เข้าแถว",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_flagpole_dashboard",
        createdAt: new Date(),
      },
      {
        title: "รายงานการเข้าแถวหน้าเสาธง",
        href: "/dashboard/flagpole-reports",
        icon: "FileText",
        desc: "พิมพ์รายงานสรุปเข้าแถว",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_flagpole_reports",
        createdAt: new Date(),
      },
      {
        title: "ตรวจสอบข้อมูลนักเรียน",
        href: "/student-data-validation",
        icon: "ShieldCheck",
        desc: "ระบบตรวจสอบความถูกต้องของข้อมูลส่วนตัว",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_student_data_validation",
        createdAt: new Date(),
      },
      {
        title: "ระบบรายงานการปฏิบัติงาน",
        href: "/work-reports",
        icon: "ClipboardList",
        desc: "พิมพ์รายงานการปฏิบัติงาน",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_work_reports",
        createdAt: new Date(),
      },
      {
        title: "ระบบข้อมูล ITA / OIT",
        href: "/dashboard/ita",
        icon: "ClipboardList",
        desc: "แก้ไขตัวชี้วัดความโปร่งใส",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "manage_ita",
        createdAt: new Date(),
      },

      // 5. Executive Workspace
      {
        title: "แดชบอร์ดติดตามงานครู",
        href: "/teacher-dashboard",
        icon: "Clock",
        desc: "สถิติติดตามการลงสอน",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "access_teacher_dashboard",
        createdAt: new Date(),
      },
      {
        title: "ตรวจสอบการจัดการเรียนการสอน",
        href: "/teacher-verification",
        icon: "CalendarCheck",
        desc: "ตรวจสอบการจัดการเรียน",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "access_teacher_verification",
        createdAt: new Date(),
      },
      {
        title: "ระบบข้อมูล ภาพรวมการเข้างาน",
        href: "/attendance-dashboard",
        icon: "CalendarCheck",
        desc: "สถิติการมาทำงาน",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_dashboard",
        createdAt: new Date(),
      },
      {
        title: "รายงานการเข้างาน",
        href: "/attendance-report",
        icon: "Clock",
        desc: "ออกรายงานสรุปการทำงาน",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_dashboard",
        createdAt: new Date(),
      },
      {
        title: "ระบบรายงานการปฏิบัติงาน",
        href: "/work-reports",
        icon: "ClipboardList",
        desc: "ตรวจสอบรายงานการปฏิบัติงาน",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_work_reports",
        createdAt: new Date(),
      },
      {
        title: "ระบบอนุมัติการลางาน",
        href: "/leave-approvals",
        icon: "CalendarCheck",
        desc: "ทบทวนและอนุมัติคำขอลาป่วย ลากิจ และตรวจสอบใบรับรองแพทย์",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_leave_approvals",
        createdAt: new Date(),
      },
      {
        title: "คำร้องรอการอนุมัติ: ระบบนิเทศการสอน",
        href: "/dashboard/supervision/requests",
        icon: "ShieldCheck",
        desc: "ตรวจสอบและจัดการรายการนิเทศที่รอการอนุมัติ",
        workspace: "executive",
        displayIn: "dashboard",
        permissionKey: "manage_supervision_requests",
        createdAt: new Date(),
      },

      // 6. Super Admin Workspace
      {
        title: "กำหนดสิทธิ์การเข้าถึงเมนูและฟังก์ชันต่างๆ แยกตามระดับผู้ใช้งาน",
        href: "/dashboard/permissions",
        icon: "Shield",
        desc: "ตรวจสอบและปรับแต่งสิทธิ์การเข้าถึงเมนูและฟังก์ชันต่างๆ",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_system",
        createdAt: new Date(),
      },
      {
        title: "จัดการสิทธิ์บุคลากร",
        href: "/manage-roles",
        icon: "UserCog",
        desc: "กำหนดบทบาทและสิทธิ์การเข้าถึงเมนูต่างๆ",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_roles_advanced",
        createdAt: new Date(),
      },
      {
        title: "ตั้งค่าระบบลงเวลาครู",
        href: "/attendance-settings",
        icon: "Settings",
        desc: "กำหนดช่วงเวลาทำงานและวันหยุดสำหรับบุคลากร",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_settings",
        createdAt: new Date(),
      },
      {
        title: "ตั้งค่าเวลาเข้าแถวหน้าเสาธง",
        href: "/dashboard/flagpole-settings",
        icon: "Settings",
        desc: "ตั้งเวลาเข้าแถวหน้าเสาธง",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_flagpole_settings",
        createdAt: new Date(),
      },
      {
        title: "ส่งข้อความแจ้งเตือนทั่วทั้งระบบ",
        href: "/broadcast-notification",
        icon: "Bell",
        desc: "ส่งข้อความแจ้งเตือนไปยังผู้ใช้ทุกคนในระบบ",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_broadcast_notification",
        createdAt: new Date(),
      },
      {
        title: "จัดการเนื้อหาหน้าหลัก",
        href: "/dashboard/manage-home",
        icon: "Globe",
        desc: "ควบคุมระบบแสดงผลและบันทึกประวัติการแก้ไขอัตโนมัติ",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_home",
        createdAt: new Date(),
      },
      {
        title: "จัดการเมนู (Navbar)",
        href: "/dashboard/navbar",
        icon: "Navigation",
        desc: "ตั้งค่าลิงก์และโครงสร้างเมนูบนหัวเว็บ",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_navbar",
        createdAt: new Date(),
      },
      {
        title: "ระบบจัดการหนังสือ (Books)",
        href: "/dashboard/books",
        icon: "BookOpen",
        desc: "สร้างและบริหารจัดการเล่มหนังสือ E-Book ทั้งหมดในระบบ",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_system",
        createdAt: new Date(),
      },
      {
        title: "จัดการเนื้อหาหน้าเว็บ (Pages)",
        href: "/dashboard/pages",
        icon: "FileText",
        desc: "สร้างหน้าเว็บใหม่ด้วย Rich Text Editor",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_pages",
        createdAt: new Date(),
      },
      {
        title: "แก้ไขข้อมูลการลงเวลา",
        href: "/dashboard/data-management",
        icon: "ClipboardList",
        desc: "แก้ไขเวลาเข้า-ออกงาน",
        workspace: "superadmin",
        displayIn: "dashboard",
        permissionKey: "manage_attendance_data",
        createdAt: new Date(),
      },

      // 7. Manuals
      {
        title: "คู่มือระบบ Gate Pass",
        href: "/manual/gate-pass",
        icon: "BookOpen",
        desc: "คู่มือการใช้งาน Gate Pass",
        workspace: "staff",
        displayIn: "dashboard",
        permissionKey: "student_dashboard",
        createdAt: new Date(),
      },
    ];

    const result = await db.collection("custom_menus").insertMany(menus);
    console.log("Inserted custom menus:", result.insertedCount);
  } catch (error) {
    console.error(error);
  } finally {
    await client.close();
  }
}

run();
